version: '3.3'
networks:
    default:
        driver: overlay
        attachable: true
services:
    zooma-mongo:
        build: .
        image: zooma:latest
        depends_on:
            - mongo
            - rabbitmq
        links:
            - mongo
            - rabbitmq
        command:
            - java
            - -jar
            - /home/zooma-mongo-3.0.0-SNAPSHOT.jar
        environment:
            - ols.term.location=http://www.ebi.ac.uk/ols/api/terms?iri=
            - spring.data.mongodb.database=zooma
            - spring.data.mongodb.port=27017
            - spring.jackson.serialization.write_dates_as_timestamps=false
            - endpoints.beans.enabled=true
            - spring.data.mongodb.host=mongo
            - spring.rabbitmq.host=rabbitmq
        ports:
            - 8080:8080
    zooma-solr:
        image: zooma:latest
        depends_on:
            - solr
            - rabbitmq
        links:
            - solr
            - rabbitmq
        command:
            - java
            - -jar
            - /home/zooma-solr-3.0.0-SNAPSHOT.jar
        environment:
            - spring.rabbitmq.host=rabbitmq
            - spring.data.solr.host=http://solr:8983/solr
            - spring.data.solr.core=annotations
            - spring.rabbitmq.activate=true
        ports:
            - 8081:8080
    zooma-neo4j:
        image: zooma:latest
        depends_on:
            - neo4j
            - rabbitmq
        links:
            - neo4j
            - rabbitmq
        healthcheck:
            #
            #  Use wget; curl not installed on the default Alpine image.
            #  Seems to perform multiple wgets, so redirect to stdout:
            #  $ wget -O - http://neo4j:7474
            #
            #  "External" and "internal" Neo4j address should both work!
            #
            test: [ "CMD", "wget", "-O", "-", "http://neo4j:7474" ]
            interval: 18s
            timeout: 12s
            retries: 3
        command:
            - sh
            - -c
            - "chmod +x /home/start_zooma_neo4j.sh; /home/start_zooma_neo4j.sh"
        environment:
            - spring.rabbitmq.host=rabbitmq
            - spring.rabbitmq.activate=true
            - spring.data.neo4j.uri=http://neo4j:7474
            #- spring.data.neo4j.username=neo4j
            - spring.data.neo4j.username=null
            - spring.data.neo4j.password=null
            - spring.data.neo4j.indexes.auto=assert
            #- spring.data.neo4j.indexes.auto=none
            - spring.jackson.serialization.write-dates-as-timestamps:false
        ports:
            - 8082:8080
    zooma-predictor:
        image: zooma:latest
        depends_on:
            - zooma-neo4j
            - zooma-solr
        links:
            - zooma-neo4j
            - zooma-solr
        environment:
            - cutoff.percentage=0.9
            - cutoff.score=80.0
            - max.ols.score=75.0
            - ols.term.location=http://www.ebi.ac.uk/ols/api/terms?iri=
            - ols.location=www.ebi.ac.uk/ols/
            - zooma.neo4j.location=http://zooma-neo4j:8080
            - zooma.solr.location=http://zooma-solr:8080
        command:
            - java
            - -jar
            - /home/zooma-predictor-3.0.0-SNAPSHOT.jar
        ports:
            - 8083:8080
    solr:
        image: solr-preconf4zooma:latest
        environment:
            - SOLR_HOME=/home/mysolrhome
        ports:
            - 8983:8983
        volumes:
            #- ./zooma-solr/src/main/sample_data/data/:/home/mysolrhome/annotation/data
            #- ./mysolrhome/:/home/mysolrhome
            - solr_data:/home/mysolrhome/annotation/data
        command: ["solr", "-f"]
    mongo:
        image: mongo:3.2
        ports:
            - 27017:27017
        volumes:
            # - ./zooma-mongo/src/main/sample_data/:/data/db
            - mongo_data:/data/db
        command:
            - mongod
    rabbitmq:
        image: rabbitmq:3.6-management
        hostname: zooma-rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@zooma-rabbitmq
    neo4j:
        image: neo4j:3.1-enterprise
        environment:
            - NEO4J_AUTH=none
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            # - ./zooma-neo4j/src/main/sample_data/:/data
            - neo4j_data:/data
volumes:
    rabbitmq_data: null
    solr_data:
    mongo_data:
    neo4j_data:
